### ISSUE TITLE
Flux may be leaking files in /tmp

### ISSUE THREAD

**Issue by groodt** [fluxcd/flux#2713]
**Describe the bug**
Flux fills up /tmp

**To Reproduce**
Large monorepo. Flux runs fine for a few days, then slowly leaks disk and then ultimately runs out of space. I've mounted a PVC at /tmp so that it doesn't consume disk on the node itself.

**Expected behavior**
Fluxcd should probably clean-up after itself?

**Logs**
```
ts=2019-12-27T00:58:18.491235642Z caller=images.go:23 component=sync-loop error="getting unlocked automated resources: mkdir /tmp/flux-working546801009: no space left on device"
```

**Additional context**
Add any other context about the problem here, e.g 
- Flux version: 1.17.0

**Comment by 2opremio** [comment]
Can you list what's in tmp? How many directories? How much does each one
occupy? Can you show us the rest of the logs?

**Comment by groodt** [comment]
I've removed the PVC now and letting it grow to fill up the host volume until it gets evicted on disk pressure.

This is what I'm currently seeing:

```
bash-5.0# cd /tmp
bash-5.0# ls -la
total 24
drwxrwxrwt    1 root     root           210 Dec 27 23:49 .
drwxr-xr-x    1 root     root            62 Dec 27 03:55 ..
drwx------    7 root     root           156 Dec 27 07:08 flux-gitclone589837000
drwx------   22 root     root          4096 Dec 27 03:58 flux-working047812410
drwx------   22 root     root          4096 Dec 27 07:09 flux-working102335891
drwx------   22 root     root          4096 Dec 27 06:02 flux-working187868532
drwx------   22 root     root          4096 Dec 27 04:22 flux-working298972273
drwx------   22 root     root          4096 Dec 27 04:12 flux-working660156126
drwx------   22 root     root          4096 Dec 27 04:34 flux-working917047553
bash-5.0# du -sh .
4.5G	.
bash-5.0# du -sh *
627.2M	flux-gitclone589837000
1.3G	flux-working047812410
1.3G	flux-working102335891
1.3G	flux-working187868532
1.3G	flux-working298972273
1.3G	flux-working660156126
1.3G	flux-working917047553
bash-5.0#
```

**Comment by groodt** [comment]
Here's an example of an eviction message from before I tried mounting a PVC at `/tmp`

```
Name:           flux-5785f78767-w29wb
Namespace:      flux
Priority:       0
Node:           ip-10-0-78-34.ec2.internal/
Start Time:     Mon, 23 Dec 2019 13:57:48 +1100
Labels:         name=flux
                pod-template-hash=5785f78767
Annotations:    kubernetes.io/psp: eks.privileged
                prometheus.io/port: 3031
Status:         Failed
Reason:         Evicted
Message:        Pod The node had condition: [DiskPressure].
```

When I saw the evictions happening, I thought that I could add a large PVC to give flux longer runway, but instead of evictions, it eventually runs into `no space left on device`. I unfortunately don't have more logs to hand of this happening. I can add back a PVC to reproduce if necessary. It might take a while to happen though, as it only seems to happen after running for some time and after handling some updates.

**Comment by 2opremio** [comment]
It may not be a leak (Flux creates a main clone and then an additional
clone for each operation). If the clones end up disappearing eventually, it
could simply have happened during an active period.

**Comment by groodt** [comment]
Ok, this implies a few things. Can you please confirm for my understanding?

1. Flux can only use a host filesystem (not possible to run fluxcd on a cluster of nodes without disks) because it relies on automated clean-up of /tmp outside fluxcd.
2. It relies on the /tmp clean-up semantics of the underlying nodes. This varies by distro. Sometimes only on boot, sometimes using tmpwatch etc.
3. Before sizing the disks on the kubernetes nodes, one needs to consider the size of the repo being cloned and the frequency of changes?

**Comment by 2opremio** [comment]
Flux cleans after itself, but it will create a local clone for each
operation it applies on the repository.

**Comment by 2opremio** [comment]
About (3), in the case of a very big repo I guess that's the case. It's not
usually a problem with usual repos.

**Comment by groodt** [comment]
Thanks for the replies.

> Flux cleans after itself, but it will create a local clone for each operation it applies on the repository.

Ok, this sounds good. Do you have more information about how frequently clean-up is happening or if there is a mechanism to configure it? I looked briefly at the code and nothing jumped out at me. If fluxcd is cleaning up after itself predictably, then it is possible to mount a PVC to /tmp as long as it is appropriately sized for the size of the repo (+ future growth of the repo) and the number of copies that flux keeps around. This would make item 1 and 2 not that much of an issue.

> About (3), in the case of a very big repo I guess that's the case. It's not usually a problem with usual repos.

For the monorepo I've got my hands on at the moment, after `git gc` I'm seeing ~500MB. Surprised me too. It seems that Terraform state files are larger than one might think. There isn't much that I can do really, apart from convincing for a new repo, which is a large ask for something running out of disk space. I would be happy to throw 200-250GB of EBS at `/tmp` for example if I could be relatively sure that I won't run out of space too quickly. At the moment, it seems like every change is taking ~1GB and not reclaiming. I don't know why it's not ~500MB, probably gc compacts it a lot locally. So after ~200 changes, flux would stop working, which isn't great. Another option I guess would be to use a PVC and make sure that the pod gets killed every so often somehow. Any ideas?

**Comment by groodt** [comment]
Another update on this, it happened again. The pod goes into `CrashLookBackOff` so it's not possible to get onto the container to see the contents of `/tmp`.

**Comment by 2opremio** [comment]
> Ok, this sounds good. Do you have more information about how frequently clean-up is happening or if there is a mechanism to configure it?

Flux has a main _mirror_ clone which periodically fetches from the repository pointed to by `--git-url`. This mirror is never removed.

On top of that, Flux creates a working clone from the _mirror_ clone every time it performs an operation (such as automatically updating an image version).  The working clone should be removed as soon as the operation is finished.

> For the monorepo I've got my hands on at the moment, after git gc I'm seeing ~500MB. Surprised me too.

I would need to know more details about the repo's activity but I would be surprised you would have an issue after giving Flux say 20 GB.


> Another update on this, it happened again. The pod goes into `CrashLookBackOff` so it's not possible to get onto the container to see the contents of `/tmp`.

Could you leave a script running which periodically prints out a summary of what's in `tmp`?

I am also interested in the flux logs. Leaks may be happening due to some error during the existence of the working clone, leading to a codepath which doesn't clean the clone properly.

**Comment by groodt** [comment]
We've run out of space again and had to restart flux. After running for approximately 24h, this is what we see:

```
❯ kubectl -n flux get po
Enter MFA code for arn:aws:iam::963070018902:mfa/greg:
NAME                         READY     STATUS    RESTARTS   AGE
flux-7499cd866f-kgsqh        1/1       Running   0          23h
```

exec into pod:
```
bash-5.0# df -ah /tmp
Filesystem                Size      Used Available Use% Mounted on
/dev/nvme1n1             49.1G      8.5G     40.6G  17% /tmp
bash-5.0# ls -la /tmp
total 68
drwxr-xr-x   15 root     root          4096 Jan 25 03:24 .
drwxr-xr-x    1 root     root            51 Jan 24 03:23 ..
drwx------    7 root     root          4096 Jan 24 06:45 flux-gitclone162428788
drwx------   23 root     root          4096 Jan 24 04:51 flux-working014604578
drwx------   23 root     root          4096 Jan 24 06:45 flux-working247434560
drwx------   23 root     root          4096 Jan 24 05:00 flux-working277166046
drwx------   23 root     root          4096 Jan 24 03:26 flux-working464685254
drwx------   23 root     root          4096 Jan 24 04:31 flux-working596953207
drwx------   23 root     root          4096 Jan 24 04:00 flux-working617540452
drwx------   23 root     root          4096 Jan 24 06:36 flux-working740637988
drwx------   23 root     root          4096 Jan 24 06:08 flux-working746937199
drwx------   23 root     root          4096 Jan 24 03:36 flux-working891134660
drwx------   23 root     root          4096 Jan 24 05:42 flux-working901227618
drwx------   23 root     root          4096 Jan 24 03:36 flux-working996116118
drwx------    2 root     root         16384 Jan 24 03:23 lost+found
```

Logs: I'll email you to your personal email due to the verbosity and potentially sensitive nature, but I don't see any indications of errors in the logs.

**Comment by groodt** [comment]
Update after ~19h.

Same pod.
```
NAME                         READY     STATUS    RESTARTS   AGE
flux-7499cd866f-kgsqh        1/1       Running   0          1d
```

Exec into Pod:
```
bash-5.0# df -ah /tmp
Filesystem                Size      Used Available Use% Mounted on
/dev/nvme1n1             49.1G      8.5G     40.6G  17% /tmp

bash-5.0# ls -la /tmp
total 72
drwxr-xr-x   16 root     root          4096 Jan 25 22:58 .
drwxr-xr-x    1 root     root            51 Jan 24 03:23 ..
drwx------    7 root     root          4096 Jan 24 06:45 flux-gitclone162428788
drwx------   23 root     root          4096 Jan 24 04:51 flux-working014604578
drwx------   23 root     root          4096 Jan 24 06:45 flux-working247434560
drwx------   23 root     root          4096 Jan 24 05:00 flux-working277166046
drwx------    7 root     root          4096 Jan 25 22:58 flux-working409479553
drwx------   23 root     root          4096 Jan 24 03:26 flux-working464685254
drwx------   23 root     root          4096 Jan 24 04:31 flux-working596953207
drwx------   23 root     root          4096 Jan 24 04:00 flux-working617540452
drwx------   23 root     root          4096 Jan 24 06:36 flux-working740637988
drwx------   23 root     root          4096 Jan 24 06:08 flux-working746937199
drwx------   23 root     root          4096 Jan 24 03:36 flux-working891134660
drwx------   23 root     root          4096 Jan 24 05:42 flux-working901227618
drwx------   23 root     root          4096 Jan 24 03:36 flux-working996116118
drwx------    2 root     root         16384 Jan 24 03:23 lost+found

bash-5.0# du -sh /tmp/*
669.7M	/tmp/flux-gitclone162428788
1.4G	/tmp/flux-working014604578
1.4G	/tmp/flux-working247434560
1.4G	/tmp/flux-working277166046
1.4G	/tmp/flux-working464685254
1.4G	/tmp/flux-working596953207
1.4G	/tmp/flux-working617540452
1.4G	/tmp/flux-working740637988
1.4G	/tmp/flux-working746937199
1.4G	/tmp/flux-working891134660
1.4G	/tmp/flux-working901227618
1.4G	/tmp/flux-working996116118
16.0K	/tmp/lost+found
```

So far, it appears nothing has leaked in the last 19h, while there have also been no automated updates to the cluster.

Next time, I'll run a test with a trivial change or addition of a resource to kick flux into action to see the impact on /tmp.

**Comment by groodt** [comment]
~24h since previous check. Some evidence of leakage. There have been no automated updates to resources by flux.

Same pod.
```
NAME                         READY     STATUS    RESTARTS   AGE
flux-7499cd866f-kgsqh        1/1       Running   0          2d
```

Exec into Pod:
```
bash-5.0# df -ah /tmp
Filesystem                Size      Used Available Use% Mounted on
/dev/nvme1n1             49.1G      9.2G     39.8G  19% /tmp
bash-5.0# ls -la /tmp
total 76
drwxr-xr-x   17 root     root          4096 Jan 26 23:40 .
drwxr-xr-x    1 root     root            51 Jan 24 03:23 ..
drwx------    7 root     root          4096 Jan 25 23:12 flux-gitclone162428788
drwx------   23 root     root          4096 Jan 24 04:51 flux-working014604578
drwx------   23 root     root          4096 Jan 24 06:45 flux-working247434560
drwx------   23 root     root          4096 Jan 24 05:00 flux-working277166046
drwx------   23 root     root          4096 Jan 24 03:26 flux-working464685254
drwx------   23 root     root          4096 Jan 25 23:12 flux-working575359694
drwx------   23 root     root          4096 Jan 24 04:31 flux-working596953207
drwx------   23 root     root          4096 Jan 24 04:00 flux-working617540452
drwx------    7 root     root          4096 Jan 26 23:40 flux-working624824473
drwx------   23 root     root          4096 Jan 24 06:36 flux-working740637988
drwx------   23 root     root          4096 Jan 24 06:08 flux-working746937199
drwx------   23 root     root          4096 Jan 24 03:36 flux-working891134660
drwx------   23 root     root          4096 Jan 24 05:42 flux-working901227618
drwx------   23 root     root          4096 Jan 24 03:36 flux-working996116118
drwx------    2 root     root         16384 Jan 24 03:23 lost+found
bash-5.0# du -sh /tmp/*
669.8M	/tmp/flux-gitclone162428788
1.4G	/tmp/flux-working014604578
1.4G	/tmp/flux-working247434560
1.4G	/tmp/flux-working277166046
1.4G	/tmp/flux-working464685254
1.4G	/tmp/flux-working575359694
1.4G	/tmp/flux-working596953207
1.4G	/tmp/flux-working617540452
1.4G	/tmp/flux-working740637988
1.4G	/tmp/flux-working746937199
1.4G	/tmp/flux-working891134660
1.4G	/tmp/flux-working901227618
1.4G	/tmp/flux-working996116118
16.0K	/tmp/lost+found
```

`/tmp/flux-working575359694` is new since the previous listing.

I'm now going to have flux create a namespace resource to see what happens to the listings and available space.

**Comment by groodt** [comment]
After flux applied a resource change (created a namespace) the contents of /tmp is as follows:

```
bash-5.0# df -ah /tmp
Filesystem                Size      Used Available Use% Mounted on
/dev/nvme1n1             49.1G      9.9G     39.1G  20% /tmp
bash-5.0# ls -la /tmp
total 76
drwxr-xr-x   17 root     root          4096 Jan 27 00:09 .
drwxr-xr-x    1 root     root            51 Jan 24 03:23 ..
drwx------    7 root     root          4096 Jan 27 00:07 flux-gitclone162428788
drwx------   23 root     root          4096 Jan 24 04:51 flux-working014604578
drwx------   23 root     root          4096 Jan 27 00:07 flux-working076747204
drwx------   23 root     root          4096 Jan 24 06:45 flux-working247434560
drwx------   23 root     root          4096 Jan 24 05:00 flux-working277166046
drwx------   23 root     root          4096 Jan 24 03:26 flux-working464685254
drwx------   23 root     root          4096 Jan 25 23:12 flux-working575359694
drwx------   23 root     root          4096 Jan 24 04:31 flux-working596953207
drwx------   23 root     root          4096 Jan 24 04:00 flux-working617540452
drwx------   23 root     root          4096 Jan 24 06:36 flux-working740637988
drwx------   23 root     root          4096 Jan 24 06:08 flux-working746937199
drwx------   23 root     root          4096 Jan 24 03:36 flux-working891134660
drwx------   23 root     root          4096 Jan 24 05:42 flux-working901227618
drwx------   23 root     root          4096 Jan 24 03:36 flux-working996116118
drwx------    2 root     root         16384 Jan 24 03:23 lost+found
bash-5.0# du -sh /tmp/*
670.0M	/tmp/flux-gitclone162428788
1.4G	/tmp/flux-working014604578
1.4G	/tmp/flux-working076747204
1.4G	/tmp/flux-working247434560
1.4G	/tmp/flux-working277166046
1.4G	/tmp/flux-working464685254
1.4G	/tmp/flux-working575359694
1.4G	/tmp/flux-working596953207
1.4G	/tmp/flux-working617540452
1.4G	/tmp/flux-working740637988
1.4G	/tmp/flux-working746937199
1.4G	/tmp/flux-working891134660
1.4G	/tmp/flux-working901227618
1.4G	/tmp/flux-working996116118
16.0K	/tmp/lost+found
```

This time `flux-working076747204` appears to be a new leak. I've also captured the logs.

**Comment by groodt** [comment]
Certainly appears that whenever flux makes a change, there are directories leaking.

```
bash-5.0# df -ah /tmp
Filesystem                Size      Used Available Use% Mounted on
/dev/nvme1n1             49.1G     10.7G     38.4G  22% /tmp
bash-5.0# ls -la /tmp
total 84
drwxr-xr-x   19 root     root          4096 Jan 27 00:24 .
drwxr-xr-x    1 root     root            51 Jan 24 03:23 ..
drwx------    7 root     root          4096 Jan 27 00:21 flux-gitclone162428788
drwx------   23 root     root          4096 Jan 24 04:51 flux-working014604578
drwx------    7 root     root          4096 Jan 27 00:24 flux-working063421434
drwx------   23 root     root          4096 Jan 27 00:07 flux-working076747204
drwx------   23 root     root          4096 Jan 24 06:45 flux-working247434560
drwx------   23 root     root          4096 Jan 24 05:00 flux-working277166046
drwx------   23 root     root          4096 Jan 24 03:26 flux-working464685254
drwx------   23 root     root          4096 Jan 25 23:12 flux-working575359694
drwx------   23 root     root          4096 Jan 24 04:31 flux-working596953207
drwx------   23 root     root          4096 Jan 24 04:00 flux-working617540452
drwx------   23 root     root          4096 Jan 24 06:36 flux-working740637988
drwx------   23 root     root          4096 Jan 24 06:08 flux-working746937199
drwx------   23 root     root          4096 Jan 24 03:36 flux-working891134660
drwx------   23 root     root          4096 Jan 24 05:42 flux-working901227618
drwx------   23 root     root          4096 Jan 27 00:21 flux-working941249421
drwx------   23 root     root          4096 Jan 24 03:36 flux-working996116118
drwx------    2 root     root         16384 Jan 24 03:23 lost+found
bash-5.0# du -sh /tmp/*
670.1M	/tmp/flux-gitclone162428788
1.4G	/tmp/flux-working014604578
1.4G	/tmp/flux-working063421434
1.4G	/tmp/flux-working076747204
1.4G	/tmp/flux-working247434560
1.4G	/tmp/flux-working277166046
1.4G	/tmp/flux-working464685254
1.4G	/tmp/flux-working575359694
1.4G	/tmp/flux-working596953207
1.4G	/tmp/flux-working617540452
1.4G	/tmp/flux-working740637988
1.4G	/tmp/flux-working746937199
1.4G	/tmp/flux-working891134660
1.4G	/tmp/flux-working901227618
1.4G	/tmp/flux-working941249421
1.4G	/tmp/flux-working996116118
16.0K	/tmp/lost+found
```

This time `/tmp/flux-working941249421` and `/tmp/tmp/flux-working063421434` are new leaks. There were 2 changes applied by flux automatically and 2 newly leaked directories. Seems too much of a coincidence to be unrelated.

**Comment by groodt** [comment]
I've now run this on the pod to delete directories older than 5h:
`find /tmp -type d -name 'flux-working*' -maxdepth 1 -mmin +300 -exec rm -rf {} \;`

The listing is now:
```
bash-5.0# df -ah /tmp
Filesystem                Size      Used Available Use% Mounted on
/dev/nvme1n1             49.1G      2.8G     46.2G   6% /tmp
bash-5.0# ls -la /tmp
total 36
drwxr-xr-x    7 root     root          4096 Jan 27 00:58 .
drwxr-xr-x    1 root     root            51 Jan 24 03:23 ..
drwx------    7 root     root          4096 Jan 27 00:24 flux-gitclone162428788
drwx------   23 root     root          4096 Jan 27 00:07 flux-working076747204
drwx------   23 root     root          4096 Jan 27 00:24 flux-working680104764
drwx------   23 root     root          4096 Jan 27 00:21 flux-working941249421
drwx------    2 root     root         16384 Jan 24 03:23 lost+found
bash-5.0# du -sh /tmp/*
670.1M	/tmp/flux-gitclone162428788
1.4G	/tmp/flux-working076747204
1.4G	/tmp/flux-working680104764
1.4G	/tmp/flux-working941249421
16.0K	/tmp/lost+found
```

I will keep an eye on this the next few days for further leaks and look into ways of automatically cleaning up old files.

**Comment by 2opremio** [comment]
Great. I will also take a look at the logs you sent me and I will go through the working-directory code looking for leaks.

If you could give further information about the automatic updates which you think caused the last two leaks (e.g. logs and nature of them) that would be helpful

**Comment by 2opremio** [comment]
I think I may have fixed this in https://github.com/fluxcd/flux/pull/2788

@groodt would you mind trying out container image `2opremio/flux:more-robust-clone-cleanup-3c3c0c9d` to confirm?

**Comment by groodt** [comment]
Amazing! Thanks!

Trying it out now and will keep an eye on it over the next few days.

```
❯ kubectl -n flux get deployment flux -o=jsonpath='{$.spec.template.spec.containers[:1].image}'
docker.io/2opremio/flux:more-robust-clone-cleanup-3c3c0c9d

bash-5.0# df -ah /tmp
Filesystem                Size      Used Available Use% Mounted on
/dev/nvme1n1             49.1G    717.9M     48.4G   1% /tmp

bash-5.0# ls -la /tmp
total 24
drwxr-xr-x    4 root     root          4096 Jan 27 07:04 .
drwxr-xr-x    1 root     root            51 Jan 27 06:56 ..
drwx------    7 root     root          4096 Jan 27 06:59 flux-gitclone379546054
drwx------    2 root     root         16384 Jan 24 03:23 lost+found

bash-5.0# du -sh /tmp/*
665.9M	/tmp/flux-gitclone379546054
16.0K	/tmp/lost+found
```

**Comment by 2opremio** [comment]
Reopening until I get a confirmation from @groodt that we fixed the problem

**Comment by bheesham** [comment]
I believe I may be seeing a similar thing. This pod has been running for a while:

```
/tmp # du -sh .
7.2G    .
/tmp # ls -l | wc -l
188
```

Each of the working copies is ~144M.

Once this happens Flux fails to apply any configs, logging the following quite often:

```
{
caller: sync.go:548
cmd: kubectl apply -f -
err: running kubectl: 
errStatus: Error
method: Sync
output: took: 256.059441ms
ts: 2020-01-27T17:53:47.502774212Z
}
```

Image: docker.io/fluxcd/flux:1.17.0

**Comment by stefanprodan** [comment]
@bheesham have you tried `2opremio/flux:more-robust-clone-cleanup-3c3c0c9d`?

**Comment by bheesham** [comment]
@stefanprodan I have not. I'll try it out on our daily environments and report back.

**Comment by groodt** [comment]
@2opremio Thanks so much.

I believe the problem we've been seeing has been fixed. I've tested the `2opremio/flux:more-robust-clone-cleanup-3c3c0c9d` image overnight (~14h) and saw no leaks.

I then had flux make 2 Kubernetes resource changes (adding a namespace and then removing a namespace, not in the same commit) and while watching both changes apply, I saw the `/tmp/flux-working*` directories get created and then removed.

I think we can consider this resolved with #2788.

**Comment by 2opremio** [comment]
Fantastic! Thanks _you_ @groodt for your persistence!

**Comment by bheesham** [comment]
Similar results here with the image you provided (though only have data for about 2 hours).

Thank you!

**Comment by magnusja** [comment]
I have the same problem. Currently flux is using about 500GB of space with thousands of flux-working directories.

I am using v1.20.2 which I guess should include the fix?

Is it cool if I just delete these for now?

**Comment by magnusja** [comment]
Yeah so I am pretty sure that this bug is still in the latest version 1.21.0

![IMG_7285](https://user-images.githubusercontent.com/1659457/97589753-349ca200-19fe-11eb-8d45-44fdf4876393.JPG)

can we reopen this or should I create a new issue?

**Comment by vdvince9874** [comment]
I confirm @magnusja. That bug seems to be back in 1.21.0.
We had that problem since ~one week. Cleaning of /tmp was not done.
Flux was upgraded from 1.19.0 to 1.21.0 ~two weeks ago.
Rollback to 1.19.0 solved the issue.

**Comment by magnusja** [comment]
```
44K     ./diff/tmp/flux-working905991546/data-keeper/data-keeper-image/tests/integration_tests
220K    ./diff/tmp/flux-working905991546/data-keeper/data-keeper-image/tests
500K    ./diff/tmp/flux-working905991546/data-keeper/data-keeper-image
584K    ./diff/tmp/flux-working905991546/data-keeper
36K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper/charts
12K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper/templates/model-keeper
16K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper/templates/mlflow
8,0K    ./diff/tmp/flux-working905991546/model-keeper/model-keeper/templates/tests
48K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper/templates
108K    ./diff/tmp/flux-working905991546/model-keeper/model-keeper
8,0K    ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/openapi/paths
8,0K    ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/openapi/components
28K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/openapi
8,0K    ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/src/model_keeper/api/endpoints
20K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/src/model_keeper/api
52K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/src/model_keeper
56K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/src
24K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/mlflow-plugin/lumi_mlflow
96K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/mlflow-plugin
20K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/docker
8,0K    ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/tests/unit_tests
20K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/tests/integration_tests
36K     ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image/tests
332K    ./diff/tmp/flux-working905991546/model-keeper/model-keeper-image
444K    ./diff/tmp/flux-working905991546/model-keeper
28K     ./diff/tmp/flux-working905991546/devbox
36K     ./diff/tmp/flux-working905991546/gateway/gateway/charts
32K     ./diff/tmp/flux-working905991546/gateway/gateway/templates
92K     ./diff/tmp/flux-working905991546/gateway/gateway
28K     ./diff/tmp/flux-working905991546/gateway/gateway-image/src/gateway/api/routers
32K     ./diff/tmp/flux-working905991546/gateway/gateway-image/src/gateway/api
88K     ./diff/tmp/flux-working905991546/gateway/gateway-image/src/gateway
92K     ./diff/tmp/flux-working905991546/gateway/gateway-image/src
16K     ./diff/tmp/flux-working905991546/gateway/gateway-image/docker
16K     ./diff/tmp/flux-working905991546/gateway/gateway-image/tests/mock_integration_tests
16K     ./diff/tmp/flux-working905991546/gateway/gateway-image/tests/unit_tests
22M     ./diff/tmp/flux-working905991546/gateway/gateway-image/tests/assets/data
22M     ./diff/tmp/flux-working905991546/gateway/gateway-image/tests/assets
104K    ./diff/tmp/flux-working905991546/gateway/gateway-image/tests/integration_tests
22M     ./diff/tmp/flux-working905991546/gateway/gateway-image/tests
23M     ./diff/tmp/flux-working905991546/gateway/gateway-image
8,0K    ./diff/tmp/flux-working905991546/gateway/ocr-worker-image/docker
52K     ./diff/tmp/flux-working905991546/gateway/ocr-worker-image
23M     ./diff/tmp/flux-working905991546/gateway
16K     ./diff/tmp/flux-working905991546/training/src/training/logger
12K     ./diff/tmp/flux-working905991546/training/src/training/datasource
44K     ./diff/tmp/flux-working905991546/training/src/training
56K     ./diff/tmp/flux-working905991546/training/src
16K     ./diff/tmp/flux-working905991546/training/docker
12K     ./diff/tmp/flux-working905991546/training/tests/unit_tests
8,0K    ./diff/tmp/flux-working905991546/training/tests/assets/scripts
1,5M    ./diff/tmp/flux-working905991546/training/tests/assets/data
1,5M    ./diff/tmp/flux-working905991546/training/tests/assets
44K     ./diff/tmp/flux-working905991546/training/tests/integration_tests/logger
60K     ./diff/tmp/flux-working905991546/training/tests/integration_tests
1,6M    ./diff/tmp/flux-working905991546/training/tests
164K    ./diff/tmp/flux-working905991546/training/deps
2,1M    ./diff/tmp/flux-working905991546/training
16K     ./diff/tmp/flux-working905991546/inference/inference/templates
36K     ./diff/tmp/flux-working905991546/inference/inference
12K     ./diff/tmp/flux-working905991546/inference/inference-image/src/inference/api/routers
16K     ./diff/tmp/flux-working905991546/inference/inference-image/src/inference/api
36K     ./diff/tmp/flux-working905991546/inference/inference-image/src/inference
40K     ./diff/tmp/flux-working905991546/inference/inference-image/src
20K     ./diff/tmp/flux-working905991546/inference/inference-image/docker
41M     ./diff/tmp/flux-working905991546/inference/inference-image/tests/assets/classification
81M     ./diff/tmp/flux-working905991546/inference/inference-image/tests/assets/exported_color_bw
121M    ./diff/tmp/flux-working905991546/inference/inference-image/tests/assets
8,0K    ./diff/tmp/flux-working905991546/inference/inference-image/tests/integration_tests
121M    ./diff/tmp/flux-working905991546/inference/inference-image/tests
164K    ./diff/tmp/flux-working905991546/inference/inference-image/deps
121M    ./diff/tmp/flux-working905991546/inference/inference-image
121M    ./diff/tmp/flux-working905991546/inference
8,0K    ./diff/tmp/flux-working905991546/docs/docker
1,3M    ./diff/tmp/flux-working905991546/docs/docs/assets/images
1,4M    ./diff/tmp/flux-working905991546/docs/docs/assets
3,0M    ./diff/tmp/flux-working905991546/docs/docs
3,0M    ./diff/tmp/flux-working905991546/docs
24K     ./diff/tmp/flux-working905991546/inference-orchestrator/inference-orchestrator-image/src/inference_orchestrator
28K     ./diff/tmp/flux-working905991546/inference-orchestrator/inference-orchestrator-image/src
8,0K    ./diff/tmp/flux-working905991546/inference-orchestrator/inference-orchestrator-image/docker
12K     ./diff/tmp/flux-working905991546/inference-orchestrator/inference-orchestrator-image/tests
72K     ./diff/tmp/flux-working905991546/inference-orchestrator/inference-orchestrator-image
16K     ./diff/tmp/flux-working905991546/inference-orchestrator/inference-operator-image/src
8,0K    ./diff/tmp/flux-working905991546/inference-orchestrator/inference-operator-image/docker
8,0K    ./diff/tmp/flux-working905991546/inference-orchestrator/inference-operator-image/tests
76K     ./diff/tmp/flux-working905991546/inference-orchestrator/inference-operator-image
16K     ./diff/tmp/flux-working905991546/inference-orchestrator/inference-orchestrator/templates/inference-operator
20K     ./diff/tmp/flux-working905991546/inference-orchestrator/inference-orchestrator/templates/inference-orchestrator
48K     ./diff/tmp/flux-working905991546/inference-orchestrator/inference-orchestrator/templates
68K     ./diff/tmp/flux-working905991546/inference-orchestrator/inference-orchestrator
220K    ./diff/tmp/flux-working905991546/inference-orchestrator
16K     ./diff/tmp/flux-working905991546/cluster
12K     ./diff/tmp/flux-working905991546/training-orchestrator/training-operator-image/src
8,0K    ./diff/tmp/flux-working905991546/training-orchestrator/training-operator-image/docker
64K     ./diff/tmp/flux-working905991546/training-orchestrator/training-operator-image
48K     ./diff/tmp/flux-working905991546/training-orchestrator/training-orchestrator-image/src/training_orchestrator
52K     ./diff/tmp/flux-working905991546/training-orchestrator/training-orchestrator-image/src
8,0K    ./diff/tmp/flux-working905991546/training-orchestrator/training-orchestrator-image/docker
96K     ./diff/tmp/flux-working905991546/training-orchestrator/training-orchestrator-image/tests
180K    ./diff/tmp/flux-working905991546/training-orchestrator/training-orchestrator-image
16K     ./diff/tmp/flux-working905991546/training-orchestrator/training-orchestrator/templates/training-operator
20K     ./diff/tmp/flux-working905991546/training-orchestrator/training-orchestrator/templates/training-orchestrator
48K     ./diff/tmp/flux-working905991546/training-orchestrator/training-orchestrator/templates
72K     ./diff/tmp/flux-working905991546/training-orchestrator/training-orchestrator
324K    ./diff/tmp/flux-working905991546/training-orchestrator
8,0K    ./diff/tmp/flux-working905991546/.git/logs/refs/heads
8,0K    ./diff/tmp/flux-working905991546/.git/logs/refs/remotes/origin
12K     ./diff/tmp/flux-working905991546/.git/logs/refs/remotes
24K     ./diff/tmp/flux-working905991546/.git/logs/refs
32K     ./diff/tmp/flux-working905991546/.git/logs
8,0K    ./diff/tmp/flux-working905991546/.git/refs/heads
4,0K    ./diff/tmp/flux-working905991546/.git/refs/tags
8,0K    ./diff/tmp/flux-working905991546/.git/refs/remotes/origin
12K     ./diff/tmp/flux-working905991546/.git/refs/remotes
28K     ./diff/tmp/flux-working905991546/.git/refs
48K     ./diff/tmp/flux-working905991546/.git/hooks
8,0K    ./diff/tmp/flux-working905991546/.git/info
4,0K    ./diff/tmp/flux-working905991546/.git/branches
4,0K    ./diff/tmp/flux-working905991546/.git/objects/info
4,0K    ./diff/tmp/flux-working905991546/.git/objects/pack
12K     ./diff/tmp/flux-working905991546/.git/objects
196K    ./diff/tmp/flux-working905991546/.git
150M    ./diff/tmp/flux-working905991546
52K     ./diff/tmp/flux-working875122815/testing/end2end
56K     ./diff/tmp/flux-working875122815/testing
36K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper/charts
20K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper/templates
80K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper
40K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/openapi/paths
24K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/openapi/components
108K    ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/openapi
32K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/src/data_keeper/api/endpoints
44K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/src/data_keeper/api
24K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/src/data_keeper/database
12K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/src/data_keeper/core
104K    ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/src/data_keeper
108K    ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/src
12K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/docker
12K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/tests/unit_tests
156K    ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/tests/assets/data
160K    ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/tests/assets
44K     ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/tests/integration_tests
220K    ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image/tests
500K    ./diff/tmp/flux-working875122815/data-keeper/data-keeper-image
584K    ./diff/tmp/flux-working875122815/data-keeper
36K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper/charts
12K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper/templates/model-keeper
16K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper/templates/mlflow
8,0K    ./diff/tmp/flux-working875122815/model-keeper/model-keeper/templates/tests
48K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper/templates
108K    ./diff/tmp/flux-working875122815/model-keeper/model-keeper
8,0K    ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/openapi/paths
8,0K    ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/openapi/components
28K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/openapi
8,0K    ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/src/model_keeper/api/endpoints
20K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/src/model_keeper/api
52K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/src/model_keeper
56K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/src
24K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/mlflow-plugin/lumi_mlflow
96K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/mlflow-plugin
20K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/docker
8,0K    ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/tests/unit_tests
20K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/tests/integration_tests
36K     ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image/tests
332K    ./diff/tmp/flux-working875122815/model-keeper/model-keeper-image
444K    ./diff/tmp/flux-working875122815/model-keeper
28K     ./diff/tmp/flux-working875122815/devbox
36K     ./diff/tmp/flux-working875122815/gateway/gateway/charts
32K     ./diff/tmp/flux-working875122815/gateway/gateway/templates
92K     ./diff/tmp/flux-working875122815/gateway/gateway
28K     ./diff/tmp/flux-working875122815/gateway/gateway-image/src/gateway/api/routers
32K     ./diff/tmp/flux-working875122815/gateway/gateway-image/src/gateway/api
88K     ./diff/tmp/flux-working875122815/gateway/gateway-image/src/gateway
92K     ./diff/tmp/flux-working875122815/gateway/gateway-image/src
16K     ./diff/tmp/flux-working875122815/gateway/gateway-image/docker
16K     ./diff/tmp/flux-working875122815/gateway/gateway-image/tests/mock_integration_tests
16K     ./diff/tmp/flux-working875122815/gateway/gateway-image/tests/unit_tests
22M     ./diff/tmp/flux-working875122815/gateway/gateway-image/tests/assets/data
22M     ./diff/tmp/flux-working875122815/gateway/gateway-image/tests/assets
104K    ./diff/tmp/flux-working875122815/gateway/gateway-image/tests/integration_tests
22M     ./diff/tmp/flux-working875122815/gateway/gateway-image/tests
23M     ./diff/tmp/flux-working875122815/gateway/gateway-image
8,0K    ./diff/tmp/flux-working875122815/gateway/ocr-worker-image/docker
52K     ./diff/tmp/flux-working875122815/gateway/ocr-worker-image
23M     ./diff/tmp/flux-working875122815/gateway
16K     ./diff/tmp/flux-working875122815/training/src/training/logger
12K     ./diff/tmp/flux-working875122815/training/src/training/datasource
44K     ./diff/tmp/flux-working875122815/training/src/training
56K     ./diff/tmp/flux-working875122815/training/src
16K     ./diff/tmp/flux-working875122815/training/docker
12K     ./diff/tmp/flux-working875122815/training/tests/unit_tests
8,0K    ./diff/tmp/flux-working875122815/training/tests/assets/scripts
1,5M    ./diff/tmp/flux-working875122815/training/tests/assets/data
1,5M    ./diff/tmp/flux-working875122815/training/tests/assets
44K     ./diff/tmp/flux-working875122815/training/tests/integration_tests/logger
60K     ./diff/tmp/flux-working875122815/training/tests/integration_tests
1,6M    ./diff/tmp/flux-working875122815/training/tests
164K    ./diff/tmp/flux-working875122815/training/deps
2,1M    ./diff/tmp/flux-working875122815/training
16K     ./diff/tmp/flux-working875122815/inference/inference/templates
36K     ./diff/tmp/flux-working875122815/inference/inference
12K     ./diff/tmp/flux-working875122815/inference/inference-image/src/inference/api/routers
16K     ./diff/tmp/flux-working875122815/inference/inference-image/src/inference/api
36K     ./diff/tmp/flux-working875122815/inference/inference-image/src/inference
40K     ./diff/tmp/flux-working875122815/inference/inference-image/src
20K     ./diff/tmp/flux-working875122815/inference/inference-image/docker
41M     ./diff/tmp/flux-working875122815/inference/inference-image/tests/assets/classification
81M     ./diff/tmp/flux-working875122815/inference/inference-image/tests/assets/exported_color_bw
121M    ./diff/tmp/flux-working875122815/inference/inference-image/tests/assets
8,0K    ./diff/tmp/flux-working875122815/inference/inference-image/tests/integration_tests
121M    ./diff/tmp/flux-working875122815/inference/inference-image/tests
164K    ./diff/tmp/flux-working875122815/inference/inference-image/deps
121M    ./diff/tmp/flux-working875122815/inference/inference-image
121M    ./diff/tmp/flux-working875122815/inference
8,0K    ./diff/tmp/flux-working875122815/docs/docker
1,3M    ./diff/tmp/flux-working875122815/docs/docs/assets/images
1,4M    ./diff/tmp/flux-working875122815/docs/docs/assets
3,0M    ./diff/tmp/flux-working875122815/docs/docs
3,0M    ./diff/tmp/flux-working875122815/docs
24K     ./diff/tmp/flux-working875122815/inference-orchestrator/inference-orchestrator-image/src/inference_orchestrator
28K     ./diff/tmp/flux-working875122815/inference-orchestrator/inference-orchestrator-image/src
8,0K    ./diff/tmp/flux-working875122815/inference-orchestrator/inference-orchestrator-image/docker
12K     ./diff/tmp/flux-working875122815/inference-orchestrator/inference-orchestrator-image/tests
72K     ./diff/tmp/flux-working875122815/inference-orchestrator/inference-orchestrator-image
16K     ./diff/tmp/flux-working875122815/inference-orchestrator/inference-operator-image/src
8,0K    ./diff/tmp/flux-working875122815/inference-orchestrator/inference-operator-image/docker
8,0K    ./diff/tmp/flux-working875122815/inference-orchestrator/inference-operator-image/tests
76K     ./diff/tmp/flux-working875122815/inference-orchestrator/inference-operator-image
16K     ./diff/tmp/flux-working875122815/inference-orchestrator/inference-orchestrator/templates/inference-operator
20K     ./diff/tmp/flux-working875122815/inference-orchestrator/inference-orchestrator/templates/inference-orchestrator
48K     ./diff/tmp/flux-working875122815/inference-orchestrator/inference-orchestrator/templates
68K     ./diff/tmp/flux-working875122815/inference-orchestrator/inference-orchestrator
220K    ./diff/tmp/flux-working875122815/inference-orchestrator
16K     ./diff/tmp/flux-working875122815/cluster
12K     ./diff/tmp/flux-working875122815/training-orchestrator/training-operator-image/src
8,0K    ./diff/tmp/flux-working875122815/training-orchestrator/training-operator-image/docker
64K     ./diff/tmp/flux-working875122815/training-orchestrator/training-operator-image
48K     ./diff/tmp/flux-working875122815/training-orchestrator/training-orchestrator-image/src/training_orchestrator
52K     ./diff/tmp/flux-working875122815/training-orchestrator/training-orchestrator-image/src
8,0K    ./diff/tmp/flux-working875122815/training-orchestrator/training-orchestrator-image/docker
96K     ./diff/tmp/flux-working875122815/training-orchestrator/training-orchestrator-image/tests
180K    ./diff/tmp/flux-working875122815/training-orchestrator/training-orchestrator-image
16K     ./diff/tmp/flux-working875122815/training-orchestrator/training-orchestrator/templates/training-operator
20K     ./diff/tmp/flux-working875122815/training-orchestrator/training-orchestrator/templates/training-orchestrator
48K     ./diff/tmp/flux-working875122815/training-orchestrator/training-orchestrator/templates
72K     ./diff/tmp/flux-working875122815/training-orchestrator/training-orchestrator
324K    ./diff/tmp/flux-working875122815/training-orchestrator
8,0K    ./diff/tmp/flux-working875122815/.git/logs/refs/heads
8,0K    ./diff/tmp/flux-working875122815/.git/logs/refs/remotes/origin
12K     ./diff/tmp/flux-working875122815/.git/logs/refs/remotes
24K     ./diff/tmp/flux-working875122815/.git/logs/refs
32K     ./diff/tmp/flux-working875122815/.git/logs
8,0K    ./diff/tmp/flux-working875122815/.git/refs/heads
4,0K    ./diff/tmp/flux-working875122815/.git/refs/tags
8,0K    ./diff/tmp/flux-working875122815/.git/refs/remotes/origin
12K     ./diff/tmp/flux-working875122815/.git/refs/remotes
28K     ./diff/tmp/flux-working875122815/.git/refs
48K     ./diff/tmp/flux-working875122815/.git/hooks
8,0K    ./diff/tmp/flux-working875122815/.git/info
4,0K    ./diff/tmp/flux-working875122815/.git/branches
4,0K    ./diff/tmp/flux-working875122815/.git/objects/info
4,0K    ./diff/tmp/flux-working875122815/.git/objects/pack
12K     ./diff/tmp/flux-working875122815/.git/objects
196K    ./diff/tmp/flux-working875122815/.git
150M    ./diff/tmp/flux-working875122815
343G    ./diff/tmp
4,0K    ./diff/root/.cache/helm/repository
8,0K    ./diff/root/.cache/helm
12K     ./diff/root/.cache
4,0K    ./diff/root/.kube
4,0K    ./diff/root/.helm/repository
8,0K    ./diff/root/.helm
8,0K    ./diff/root/.config/helm
12K     ./diff/root/.config
4,0K    ./diff/root/.ssh
44K     ./diff/root
4,0K    ./diff/run/secrets/kubernetes.io/serviceaccount
8,0K    ./diff/run/secrets/kubernetes.io
12K     ./diff/run/secrets
16K     ./diff/run
343G    ./diff
4,0K    ./work/work
8,0K    ./work
686G    .
```

Unfortunately, this did not cut it for me...

**Comment by adusumillipraveen** [comment]
Is this being looked at ? We are also hitting this frequently after recent upgrade.

**Comment by magnusja** [comment]
I dont think so as v1 is obsolete. Maybe it is also necessary to to open a new issue to draw some more attention.

My hack to his is to restart the flux pod every hour. The `/tmp` is inside the pod so this gets deleted.
```yaml
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: flux-restart
  namespace: flux

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-restart
  namespace: flux
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch", "list", "watch", "delete"] 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-restart
  namespace: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-restart
subjects:
  - kind: ServiceAccount
    name: flux-restart

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: flux-pod-restart
  namespace: flux
spec:
  concurrencyPolicy: Forbid
  schedule: "0 */1 * * *" 
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: flux-restart 
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - kubectl
                - delete
                - pod
                - -l app=flux
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: flux-helm-restart
  namespace: flux
spec:
  concurrencyPolicy: Forbid
  schedule: "0 */1 * * *" 
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: flux-restart 
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - kubectl
                - delete
                - pod
                - -l app=helm-operator
```

**Comment by gengwg** [comment]
I'm seeing this issue also. Does anyone know how to delete the files? It shows /tmp is 100% used, but when I do du it's empty.

```
◎ verifying installation
✔ source-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ helm-controller: deployment ready
✔ notification-controller: deployment ready
✔ install completed
► configuring deploy key
► generating sync manifests
✔ sync manifests pushed
► applying sync manifests
◎ waiting for cluster sync
✗ tmp dir error: mkdir /tmp/flux-system140303913: no space left on device
$ kubectl exec -i -t -n flux-system helm-controller-5b47dc86b8-26p2j -- /bin/sh
/ $ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  58.4G     55.6G         0 100% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                   994.0M         0    994.0M   0% /sys/fs/cgroup
/dev/vda1                58.4G     55.6G         0 100% /tmp
/dev/vda1                58.4G     55.6G         0 100% /etc/hosts
/dev/vda1                58.4G     55.6G         0 100% /dev/termination-log
/dev/vda1                58.4G     55.6G         0 100% /etc/hostname
/dev/vda1                58.4G     55.6G         0 100% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   994.0M     12.0K    994.0M   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                   994.0M         0    994.0M   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                   994.0M         0    994.0M   0% /sys/firmware
/ $ du -sh /tmp/
4.0K	/tmp/
```

**Comment by kingdonb** [comment]
@gengwg From the looks of what you posted, your 58GB disk (Docker machine host?) is completely full and it is shared between all the filesystems of the Docker host, so the message about /tmp being full isn't because of files in /tmp at all.

If you are using Docker Machine, or Minikube, or something else that runs docker, I recommend you check inside the Docker host, or inspect it from outside using commands like `docker image ls` and `docker volume ls` to figure out if there is something you can delete. If you are using buildkit, you might get the most mileage out of `docker builder prune -a`.

Also, this issue belongs to Flux v1 but you appear to be using Flux v2. So I'm 100% sure it's not the same issue. 👍

**Comment by kingdonb** [comment]
It does look like there are recent reports of this issue which might need further investigation though.

Reopening so I do not lose track. (Does anyone have a current repro of this issue on 1.22.0?)

**Comment by gengwg** [comment]
@kingdonb thank you very much!

I did a `docker image prune -a`:

```
$ docker image prune -a
Total reclaimed space: 33.99GB
```

Now my macbook shows 99G available:

```
Filesystem       Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s5s1  466Gi   14Gi   99Gi    13%  568975 4881883905    0%   /
devfs           199Ki  199Ki    0Bi   100%     691          0  100%   /dev
/dev/disk1s4    466Gi  5.0Gi   99Gi     5%       5 4882452875    0%   /System/Volumes/VM
/dev/disk1s2    466Gi  410Mi   99Gi     1%    1393 4882451487    0%   /System/Volumes/Preboot
/dev/disk1s10   466Gi  2.1Mi   99Gi     1%      14 4882452866    0%   /System/Volumes/Update
/dev/disk1s1    466Gi  347Gi   99Gi    78% 5414294 4877038586    0%   /System/Volumes/Data
map auto_home     0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
```
After that it seems working:

```
► connecting to ghe.company.com
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► configuring deploy key
► generating sync manifests
✔ sync manifests pushed
► applying sync manifests
◎ waiting for cluster sync
✔ bootstrap finished
$ flux get kustomizations
NAME       	READY  	MESSAGE                   	REVISION                                       	SUSPENDED
flux-system	Unknown	reconciliation in progress	master/f2b3805a6b11a5172932ea428e4031ab3c7142f6	False
$ flux get kustomizations
NAME       	READY	MESSAGE                                                          	REVISION                                       	SUSPENDED
flux-system	True 	Applied revision: master/299bec4af7ac126e5c7be7d18099cd1e7a1ceef9	master/299bec4af7ac126e5c7be7d18099cd1e7a1ceef9	False
```

But i don't quite understand it. My macbook previously has 64G available. it's not totally full yet. Why it says no space left?

```
/dev/disk1s5s1  466Gi   14Gi   64Gi    19%  568975 4881883905    0%   /
```

Other info: 
I'm using KIND to create the k8s cluster:

```
$ kind version
kind v0.7.0 go1.13.6 darwin/amd64
$ kubectl cluster-info
Kubernetes master is running at https://127.0.0.1:55001
KubeDNS is running at https://127.0.0.1:55001/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

Sorry I didn't look carefully. I installed it using homebrew. I think I'm using Flux v2? (it says 0.10.0 though.)

```
$ flux -v
flux version 0.10.0
$ brew info flux
Warning: Treating flux as a formula. For the cask, use homebrew/cask/flux
flux: stable 0.100.1 (bottled), HEAD
Lightweight scripting language for querying databases
https://www.influxdata.com/products/flux/
/usr/local/Cellar/flux/0.10.0 (3 files, 49.2MB) *
  Built from source on 2021-03-23 at 12:12:03
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/flux.rb
License: MIT
==> Dependencies
Build: go ✘, rust ✘
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 568 (30 days), 1,350 (90 days), 1,739 (365 days)
install-on-request: 567 (30 days), 1,347 (90 days), 1,729 (365 days)
build-error: 0 (30 days)
```

**Comment by kingdonb** [comment]
@gengwg You are using Flux v2. The 0.10.0 indicates that it is pre-release, it is confusing because Flux 2 comes after 1 but has a lower version number. I think this will be resolved when it goes "1.0" since we cannot have two Flux 1.0 releases, but for now it remains confusing.

In kind, see the setting described in their docs for Docker Desktop, "disk image maximum size" under this heading:

https://kind.sigs.k8s.io/docs/user/quick-start/#settings-for-docker-desktop

There is a virtual disk in Docker Desktop, since it runs a separate OS kernel for Linux to run Docker on, it needs its own filesystem distinct from the one belonging to the Host OS.

It can be full while the host remains with plenty enough space. The kind docs also mention `docker system prune`. The longer you have been running Docker Desktop without cleaning up inside, the more cruft will likely accumulate in there, eventually it fills and you get some possibly quite confusing errors as you've found. Please join us on the Flux slack channel of CNCF slack for troubleshooting or if you have more questions. 👍

**Comment by kingdonb** [comment]
I'm interested in the original issue that was posted here, @magnusja are you still using Flux v1? I've taken over maintenance.

Is a hack to restart every hour still needed, I want to know more about the conditions that cause the working dir to swallow up space in the flux v1 pod, and whether it has been resolved in v1.22.0 or not. I think it might be resolved by #3282 but I don't understand well enough to merge it yet. The submitter was either not interested in merging anymore, or got tired of waiting.

I could not merge it because I did not want to merge a failing/flaky test, but if this has truly regressed and Flux v1 is really leaking in /tmp when clones time out, I'll be interested to fix it in the next release.

**Comment by kingdonb** [comment]
We worked on a similar issue, or possibly the same issue, in several recent Flux releases. If you haven't upgraded yet, please try and let me know if this still affects you.

Flux v1 is formally superseded since the GitOps Toolkit APIs have been declared stable:

https://fluxcd.io/docs/migration/timetable/

The repo will remain in maintenance for some time, but no new features can be accepted. Bugs can be addressed if they are critical and there is a PR to resolve it, but soon only CVEs can be addressed in Flux v1, and new users are all recommended to use Flux v2 for some time now.

Thanks for using Flux!

**Comment by Shabbirm21** [comment]
HI @kingdonb 

I am having same problem with flux-simulaor where even at the start of fragmentation stage I ran out if memory on my 500gb hard disk. I have used flux earlier on different machine smoothly. I have no clue what went wrong this time.
As you said we should use new release, I have version 1.2.1 that's the latest available on your website and on anaconda. But your comment is 16 days old and that version shows updated date of 2013. 

Am I missing something? from where should I download the recent version? (few links I found were already broken)

**Comment by kingdonb** [comment]
I am not sure what OS distro you have, but Flux v1 releases are posted at https://github.com/fluxcd/flux/releases

The Flux version 1.2.1 was released in 2018, I don't know what Flux version was in 2013
https://github.com/fluxcd/flux/releases/tag/1.2.1

What page are you finding these old links, so we can make sure it gets removed?

The latest Flux release at this time for Flux v1 is here:

* Flux 1.23.2
kingdonb released this 12 days ago

**Comment by kingdonb** [comment]
@Shabbirm21 I think you have us confused with https://surveillance.cancer.gov/genetic-simulation-resources/packages/flux-simulator/ -- this is a totally separate project than flux-simulator.

This project is, rather, https://fluxcd.io for Kubernetes and GitOps

**Comment by Shabbirm21** [comment]
Oh, my bad..I am sorry.

**Comment by caleygoff-invitae** [comment]
@kingdonb it seems we might be having this issue in `flux:1.24.1` I'm mentioning it here too because I noticed the linked PR is closed

**Comment by kingdonb** [comment]
I'm going to run the tests on that PR a couple of times, maybe there was no flaky test.

It is possible the issue was related to something else that went wrong at the time of running the test before, when the branch was open. Are you interested in testing a prerelease build from that branch?

**Comment by pjbgf** [comment]
This project is in Migration and security support only, so unfortunately this issue won't be fixed. We recommend users migrate to Flux 2 at their earliest convenience.

More information about the Flux 2 transition timetable can be found at: https://fluxcd.io/docs/migration/timetable/.
